//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sino.Extensions.AreaService {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Regions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Regions() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sino.Extensions.AreaService.Regions", typeof(Regions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Areas&quot;: [
        ///    {
        ///      &quot;Version&quot;: &quot;V2_SN&quot;,
        ///      &quot;Regions&quot;: [
        ///        {
        ///          &quot;Code&quot;: &quot;331083&quot;,
        ///          &quot;Name&quot;: &quot;玉环市&quot;,
        ///          &quot;Level&quot;: 3,
        ///          &quot;Version&quot;: &quot;V2_SN&quot;
        ///        },
        ///        {
        ///          &quot;Code&quot;: &quot;331100&quot;,
        ///          &quot;Name&quot;: &quot;丽水市&quot;,
        ///          &quot;Level&quot;: 2,
        ///          &quot;Version&quot;: &quot;V2_SN&quot;
        ///        },
        ///        {
        ///          &quot;Code&quot;: &quot;331102&quot;,
        ///          &quot;Name&quot;: &quot;莲都区&quot;,
        ///          &quot;Level&quot;: 3,
        ///          &quot;Version&quot;: &quot;V2_SN&quot;
        ///        },
        ///        {
        ///          &quot;Code&quot;: &quot;331121&quot;,
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
    }
}
